# config.yaml
samples: 20
triple_extraction: false
data:
  dataset: "vqa"
  root_dir: "/staging/users/tpadhi1/Multimodal-Uncertainty-Quantification/datasets_/VQA"
  image_dir: "train2014"
  annotation_file: "v1/annotations/mscoco_train2014_annotations_HIGH_agreement_question_types_GROUND.json"
  question_file: "v1/questions/OpenEnded_mscoco_train2014_questions_RANDOMSEED_42_COUNT_2000_CURRDATE_20241228_170848.json"
  dataset_type: "json"
  samples: 2000
mm_model:
  # model_path: for 7b "llava-hf/llava-1.5-7b-hf" # for 13b llava-hf/llava-1.5-13b-hf
  model_path: "llava-hf/llava-1.5-7b-hf"
  temperature: 0.5
  top_p: 1 
  num_beams: 1
  max_new_tokens: 512
  no_of_responses_sampled_per_image: 20
  inference_batch_size: 20 # this is the batch size for the model inference of llava


triples_model:
  model_id: "meta-llama/Meta-Llama-3-8B-Instruct"
grounding:
  detector_id: "IDEA-Research/grounding-dino-tiny"
  segmenter_id: "facebook/sam-vit-base"
  threshold: 0.01
  llama32_model_path_11B: "meta-llama/Llama-3.2-11B-Vision-Instruct"
  llama32_model_path_90B: "meta-llama/Llama-3.2-90B-Vision-Instruct"
  qwen_vl_25_7B_model_path: "Qwen/Qwen2.5-VL-7B-Instruct"
  qwen_vl_model_path: "Qwen/Qwen2-VL-7B-Instruct"
  gemini_model_path: 'gemini-2.0-flash'
  # dino_model_path: "path/to/dino/model"
  # top_k: 5

uncertainty:
  method: "log_likelihood"
  get_uncertainty: true

logging:
  explanation_dir: "/staging/users/tpadhi1/Multimodal-Uncertainty-Quantification/runs_vqa6/llava_vqa_yes_gsam_grounding_random_1000_temp_05/explanations_2000"
  grounding_dir_with_gdsam: "/staging/users/tpadhi1/Multimodal-Uncertainty-Quantification/runs_vqa6/llava_vqa_yes_gsam_grounding_random_1000_temp_05/grounding_with_gdsam"
  grounding_dir_with_qwen_vl: "/staging/users/tpadhi1/Multimodal-Uncertainty-Quantification/runs_vqa6/llava_vqa_yes_gsam_grounding_random_1000_temp_05/grounding_with_qwen_vl"
  grounding_dir_with_qwen_vl_25_7B: "/staging/users/tpadhi1/Multimodal-Uncertainty-Quantification/runs_vqa6/llava_vqa_yes_gsam_grounding_random_1000_temp_05/grounding_with_qwen_vl_25_7B"
  grounding_dir_with_llama32_90B: "/staging/users/tpadhi1/Multimodal-Uncertainty-Quantification/runs_vqa6/llava_vqa_yes_gsam_grounding_random_1000_temp_05/grounding_with_llama32_90B"
  grounding_dir_with_llama32_11B: "/staging/users/tpadhi1/Multimodal-Uncertainty-Quantification/runs_vqa6/llava_vqa_yes_gsam_grounding_random_1000_temp_05/grounding_with_llama32_11B"
  grounding_dir_with_gemini: "/staging/users/tpadhi1/Multimodal-Uncertainty-Quantification/runs_vqa6/llava_vqa_yes_gsam_grounding_random_1000_temp_05/grounding_with_gemini"
