model_path: "liuhaotian/llava-v1.6-vicuna-7b"
model_base: null
image_file: "path/to/image.png"
query: "Your query here"
conv_mode: null
sep: ","
temperature: 0.01
top_p: null
num_beams: 1
max_new_tokens: 512
data_path: "/home/ubuntu/Multimodal-Uncertainty-Quantification/datasets/MMT-Bench/MMT-Bench_VAL.tsv"
no_of_responses_each_sample: 20
output_path: "llava_mmt_output.json"