# config.yaml
samples: 20
triple_extraction: false
data:
  dataset: "gqa"
  data_dir: "data/gqa"
  data_path: "/home/ubuntu/Multimodal-Uncertainty-Quantification/dataset/GQA/"
  dataset_type: "json"
mm_model:
  model_path: "llava-hf/llava-1.5-7b-hf"
  temperature: 1
  top_p: 1 
  num_beams: 1
  max_new_tokens: 512
  no_of_responses_sampled_per_image: 20


triples_model:
  model_id: "meta-llama/Meta-Llama-3-8B-Instruct"
grounding:
  detector_id: "IDEA-Research/grounding-dino-tiny"
  segmenter_id: "facebook/sam-vit-base"
  threshold: 0.01
  # dino_model_path: "path/to/dino/model"
  # top_k: 5

uncertainty:
  method: "log_likelihood"
  get_uncertainty: true

logging:
  uncertainty_path: "runs/llava_gqa_llama3_sg_grounding"
  responses_path: "runs/llava_gqa_temp1"
  log_file: "llava_mmt.log"
  explanation_dir: "runs/llava_gqa_yes_gsam_grounding/explanations"
  grounding_dir: "runs/llava_gqa_yes_gsam_grounding/grounding"